server:
  port: 8080

spring:

  config:
    import: optional:file:../common/application-common.yml

  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**,/api/categories/**

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventory/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**,/api/customers/**
